// app/layout.tsx

import React, { ReactNode } from "react";
import Head from "next/head";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Furniro",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/logo.png",
  },
};

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
      </Head>
      <html lang="en" suppressHydrationWarning>
        <body>
          <ClerkProvider
            appearance={{
              elements: {
                formButtonPrimary: "primary-gradient",
                footerActionLink: "primary-text-gradient",
              },
            }}
          >
            {children}
          </ClerkProvider>
        </body>
      </html>
    </>
  );
};

export default Layout;
